name: noor_hidayat
description: رول بیسڈ اسلامی تعلیمی ایپ (بچے، خواتین، مرد)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  just_audio: ^0.9.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
    - assets/audio/
  # اردو نستعلیق فونٹ شامل کرنے کے لیے فونٹ فائل assets/fonts/ میں رکھیں اور نیچے کھولیں:
  # fonts:
  #   - family: NotoNastaliq
  #     fonts:
  #       - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
